using System;
using System.Collections.Generic;
using System.Text;

namespace KbdHookCS
{
    class vkMap
    {
        public int b;
        public string s;
        public vkMap(int b, string s)
        {
            this.b = b;
            this.s = s;
        }
        public static vkMap[] vkValues = {
                new vkMap ( 0x00, "VK_NOTDEF"), 
                new vkMap ( 0x01, "VK_LBUTTON" ),
                new vkMap ( 0x02,"VK_RBUTTON" ),
                new vkMap ( 0x03,"VK_CANCEL" ),
                new vkMap ( 0x04,"VK_MBUTTON" ),
                new vkMap ( 0x05,"undef 0x05" ),
                new vkMap ( 0x06,"undef 0x06" ),
                new vkMap ( 0x07,"undef 0x07" ),
                new vkMap ( 0x08,"VK_BACK" ),
                new vkMap ( 0x09,"VK_TAB" ),
                new vkMap ( 0x0A,"undef 0x0A" ),
                new vkMap ( 0x0B,"undef 0x0B" ),
                new vkMap ( 0x0C,"VK_CLEAR" ),
                new vkMap ( 0x0D,"VK_RETURN" ),
                new vkMap ( 0x0E,"undef 0x0E" ),
                new vkMap ( 0x0F,"undef 0x0F" ),
                new vkMap ( 0x10,"VK_SHIFT" ),
                new vkMap ( 0x11,"VK_CONTROL" ),
                new vkMap ( 0x12,"VK_MENU" ),
                new vkMap ( 0x13,"VK_PAUSE" ),
                new vkMap ( 0x14,"VK_CAPITAL" ),
                new vkMap ( 0x15,"VK_HANGUL" ),
                new vkMap ( 0x16,"undef 0x16" ),
                new vkMap ( 0x17,"VK_JUNJA" ),
                new vkMap ( 0x18,"VK_FINAL" ),
                new vkMap ( 0x19,"VK_KANJI" ),
                new vkMap ( 0x1A,"undef 0x1A" ),
                new vkMap ( 0x1B,"VK_ESCAPE" ),
                new vkMap ( 0x1C,"VK_CONVERT" ),
                new vkMap ( 0x1D,"VK_NOCONVERT" ),
                new vkMap ( 0x1E,"undef 0x1E" ),
                new vkMap ( 0x1F,"undef 0x1F" ),
                new vkMap ( 0x20,"VK_SPACE" ),
                new vkMap ( 0x21,"VK_PRIOR" ),
                new vkMap ( 0x22,"VK_NEXT" ),
                new vkMap ( 0x23,"VK_END" ),
                new vkMap ( 0x24,"VK_HOME" ),
                new vkMap ( 0x25,"VK_LEFT" ),
                new vkMap ( 0x26,"VK_UP" ),
                new vkMap ( 0x27,"VK_RIGHT" ),
                new vkMap ( 0x28,"VK_DOWN" ),
                new vkMap ( 0x29,"VK_SELECT" ),
                new vkMap ( 0x2A,"VK_PRINT" ),
                new vkMap ( 0x2B,"VK_EXECUTE" ),
                new vkMap ( 0x2C,"VK_SNAPSHOT" ),
                new vkMap ( 0x2D,"VK_INSERT" ),
                new vkMap ( 0x2E,"VK_DELETE" ),
                new vkMap ( 0x2F,"VK_HELP" ),
                new vkMap ( 0x30,"VK_0" ),
                new vkMap ( 0x31,"VK_1" ),
                new vkMap ( 0x32,"VK_2" ),
                new vkMap ( 0x33,"VK_3" ),
                new vkMap ( 0x34,"VK_4" ),
                new vkMap ( 0x35,"VK_5" ),
                new vkMap ( 0x36,"VK_6" ),
                new vkMap ( 0x37,"VK_7" ),
                new vkMap ( 0x38,"VK_8" ),
                new vkMap ( 0x39,"VK_9" ),
                new vkMap ( 0x3A,"undef 0x3A" ),
                new vkMap ( 0x3B,"undef 0x3B" ),
                new vkMap ( 0x3C,"undef 0x3C" ),
                new vkMap ( 0x3D,"undef 0x3D" ),
                new vkMap ( 0x3E,"undef 0x3E" ),
                new vkMap ( 0x3F,"undef 0x3F" ),
                new vkMap ( 0x40,"undef 0x40" ),
                new vkMap ( 0x41,"VK_A" ),
                new vkMap ( 0x42,"VK_B" ),
                new vkMap ( 0x43,"VK_C" ),
                new vkMap ( 0x44,"VK_D" ),
                new vkMap ( 0x45,"VK_E" ),
                new vkMap ( 0x46,"VK_F" ),
                new vkMap ( 0x47,"VK_G" ),
                new vkMap ( 0x48,"VK_H" ),
                new vkMap ( 0x49,"VK_I" ),
                new vkMap ( 0x4A,"VK_J" ),
                new vkMap ( 0x4B,"VK_K" ),
                new vkMap ( 0x4C,"VK_L" ),
                new vkMap ( 0x4D,"VK_M" ),
                new vkMap ( 0x4E,"VK_N" ),
                new vkMap ( 0x4F,"VK_O" ),
                new vkMap ( 0x50,"VK_P" ),
                new vkMap ( 0x51,"VK_Q" ),
                new vkMap ( 0x52,"VK_R" ),
                new vkMap ( 0x53,"VK_S" ),
                new vkMap ( 0x54,"VK_T" ),
                new vkMap ( 0x55,"VK_U" ),
                new vkMap ( 0x56,"VK_V" ),
                new vkMap ( 0x57,"VK_W" ),
                new vkMap ( 0x58,"VK_X" ),
                new vkMap ( 0x59,"VK_Y" ),
                new vkMap ( 0x5A,"VK_Z" ),
                new vkMap ( 0x5B,"VK_LWIN" ),
                new vkMap ( 0x5C,"VK_RWIN" ),
                new vkMap ( 0x5D,"VK_APPS" ),
                new vkMap ( 0x5E,"undef 0x5E" ),
                new vkMap ( 0x5F,"VK_SLEEP" ),
                new vkMap ( 0x60,"VK_NUMPAD0" ),
                new vkMap ( 0x61,"VK_NUMPAD1" ),
                new vkMap ( 0x62,"VK_NUMPAD2" ),
                new vkMap ( 0x63,"VK_NUMPAD3" ),
                new vkMap ( 0x64,"VK_NUMPAD4" ),
                new vkMap ( 0x65,"VK_NUMPAD5" ),
                new vkMap ( 0x66,"VK_NUMPAD6" ),
                new vkMap ( 0x67,"VK_NUMPAD7" ),
                new vkMap ( 0x68,"VK_NUMPAD8" ),
                new vkMap ( 0x69,"VK_NUMPAD9" ),
                new vkMap ( 0x6A,"VK_MULTIPLY" ),
                new vkMap ( 0x6B,"VK_ADD" ),
                new vkMap ( 0x6C,"VK_SEPARATOR" ),
                new vkMap ( 0x6D,"VK_SUBTRACT" ),
                new vkMap ( 0x6E,"VK_DECIMAL" ),
                new vkMap ( 0x6F,"VK_DIVIDE" ),
                new vkMap ( 0x70,"VK_F1" ),
                new vkMap ( 0x71,"VK_F2" ),
                new vkMap ( 0x72,"VK_F3" ),
                new vkMap ( 0x73,"VK_F4" ),
                new vkMap ( 0x74,"VK_F5" ),
                new vkMap ( 0x75,"VK_F6" ),
                new vkMap ( 0x76,"VK_F7" ),
                new vkMap ( 0x77,"VK_F8" ),
                new vkMap ( 0x78,"VK_F9" ),
                new vkMap ( 0x79,"VK_F10" ),
                new vkMap ( 0x7A,"VK_F11" ),
                new vkMap ( 0x7B,"VK_F12" ),
                new vkMap ( 0x7C,"VK_F13" ),
                new vkMap ( 0x7D,"VK_F14" ),
                new vkMap ( 0x7E,"VK_F15" ),
                new vkMap ( 0x7F,"VK_F16" ),
                new vkMap ( 0x80,"VK_F17" ),
                new vkMap ( 0x81,"VK_F18" ),
                new vkMap ( 0x82,"VK_F19" ),
                new vkMap ( 0x83,"VK_F20" ),
                new vkMap ( 0x84,"VK_F21" ),
                new vkMap ( 0x85,"VK_F22" ),
                new vkMap ( 0x86,"VK_F23" ),
                new vkMap ( 0x87,"VK_F24" ),
                new vkMap ( 0x88,"undef 0x88" ),
                new vkMap ( 0x89,"undef 0x89" ),
                new vkMap ( 0x8A,"undef 0x8A" ),
                new vkMap ( 0x8B,"undef 0x8B" ),
                new vkMap ( 0x8C,"undef 0x8C" ),
                new vkMap ( 0x8D,"undef 0x8D" ),
                new vkMap ( 0x8E,"undef 0x8E" ),
                new vkMap ( 0x8F,"undef 0x8F" ),
                new vkMap ( 0x90,"VK_NUMLOCK" ),
                new vkMap ( 0x91,"VK_SCROLL" ),
                new vkMap ( 0x92,"undef 0x92" ),
                new vkMap ( 0x93,"undef 0x93" ),
                new vkMap ( 0x94,"undef 0x94" ),
                new vkMap ( 0x95,"undef 0x95" ),
                new vkMap ( 0x96,"undef 0x96" ),
                new vkMap ( 0x97,"undef 0x97" ),
                new vkMap ( 0x98,"undef 0x98" ),
                new vkMap ( 0x99,"undef 0x99" ),
                new vkMap ( 0x9A,"undef 0x9A" ),
                new vkMap ( 0x9B,"undef 0x9B" ),
                new vkMap ( 0x9C,"undef 0x9C" ),
                new vkMap ( 0x9D,"undef 0x9D" ),
                new vkMap ( 0x9E,"undef 0x9E" ),
                new vkMap ( 0x9F,"undef 0x9F" ),
                new vkMap ( 0xA0,"VK_LSHIFT" ),
                new vkMap ( 0xA1,"VK_RSHIFT" ),
                new vkMap ( 0xA2,"VK_LCONTROL" ),
                new vkMap ( 0xA3,"VK_RCONTROL" ),
                new vkMap ( 0xA4,"VK_LMENU" ),
                new vkMap ( 0xA5,"VK_RMENU" ),
                new vkMap ( 0xA6,"VK_BROWSER_BACK" ),
                new vkMap ( 0xA7,"VK_BROWSER_FORWARD" ),
                new vkMap ( 0xA8,"VK_BROWSER_REFRESH" ),
                new vkMap ( 0xA9,"VK_BROWSER_STOP" ),
                new vkMap ( 0xAA,"VK_BROWSER_SEARCH" ),
                new vkMap ( 0xAB,"VK_BROWSER_FAVORITES" ),
                new vkMap ( 0xAC,"VK_BROWSER_HOME" ),
                new vkMap ( 0xAD,"VK_VOLUME_MUTE" ),
                new vkMap ( 0xAE,"VK_VOLUME_DOWN" ),
                new vkMap ( 0xAF,"VK_VOLUME_UP" ),
                new vkMap ( 0xB0,"VK_MEDIA_NEXT_TRACK" ),
                new vkMap ( 0xB1,"VK_MEDIA_PREV_TRACK" ),
                new vkMap ( 0xB2,"VK_MEDIA_STOP" ),
                new vkMap ( 0xB3,"VK_MEDIA_PLAY_PAUSE" ),
                new vkMap ( 0xB4,"VK_LAUNCH_MAIL" ),
                new vkMap ( 0xB5,"VK_LAUNCH_MEDIA_SELECT" ),
                new vkMap ( 0xB6,"VK_LAUNCH_APP1" ),
                new vkMap ( 0xB7,"VK_LAUNCH_APP2" ),
                new vkMap ( 0xB8,"undef 0xB8" ),
                new vkMap ( 0xB9,"undef 0xB9" ),
                new vkMap ( 0xBA,"VK_SEMICOLON" ),
                new vkMap ( 0xBB,"VK_EQUAL" ),
                new vkMap ( 0xBC,"VK_COMMA" ),
                new vkMap ( 0xBD,"VK_HYPHEN" ),
                new vkMap ( 0xBE,"VK_PERIOD" ),
                new vkMap ( 0xBF,"VK_SLASH" ),
                new vkMap ( 0xC0,"VK_BACKQUOTE" ),
                new vkMap ( 0xC1,"VK_APP1" ),
                new vkMap ( 0xC2,"VK_APP2" ),
                new vkMap ( 0xC3,"VK_APP3" ),
                new vkMap ( 0xC4,"VK_APP4" ),
                new vkMap ( 0xC5,"VK_APP5" ),
                new vkMap ( 0xC6,"VK_APP6" ),
                new vkMap ( 0xC7,"undef 0xC7" ),
                new vkMap ( 0xC8,"undef 0xC8" ),
                new vkMap ( 0xC9,"undef 0xC9" ),
                new vkMap ( 0xC0,"undef 0xC0" ),
                new vkMap ( 0xCA,"undef 0xCA" ),
                new vkMap ( 0xCB,"undef 0xCB" ),
                new vkMap ( 0xCC,"undef 0xCC" ),
                new vkMap ( 0xCD,"undef 0xCD" ),
                new vkMap ( 0xCE,"undef 0xCE" ),
                new vkMap ( 0xCF,"undef 0xCF" ),
                new vkMap ( 0xD0,"undef 0xD0" ),
                new vkMap ( 0xD1,"undef 0xD1" ),
                new vkMap ( 0xD2,"undef 0xD2" ),
                new vkMap ( 0xD3,"undef 0xD3" ),
                new vkMap ( 0xD4,"undef 0xD4" ),
                new vkMap ( 0xD5,"undef 0xD5" ),
                new vkMap ( 0xD6,"undef 0xD6" ),
                new vkMap ( 0xD7,"undef 0xD7" ),
                new vkMap ( 0xD8,"undef 0xD8" ),
                new vkMap ( 0xD9,"undef 0xD9" ),
                new vkMap ( 0xD0,"undef 0xD0" ),
                new vkMap ( 0xDA,"undef 0xDA" ),
                new vkMap ( 0xDB,"VK_LBRACKET" ),
                new vkMap ( 0xDC,"VK_BACKSLASH" ),
                new vkMap ( 0xDD,"VK_RBRACKET" ),
                new vkMap ( 0xDE,"VK_APOSTROPHE" ),
                new vkMap ( 0xDF,"VK_OFF" ),
                new vkMap ( 0xE0,"undef 0xE0" ),
                new vkMap ( 0xE1,"undef 0xE1" ),
                new vkMap ( 0xE2,"VK_EXTEND_BSLASH" ),
                new vkMap ( 0xE3,"undef 0xE3" ),
                new vkMap ( 0xE4,"undef 0xE4" ),
                new vkMap ( 0xE5,"VK_PROCESSKEY" ),
                new vkMap ( 0xE6,"undef 0xE6" ),
                new vkMap ( 0xE7,"undef 0xE7" ),
                new vkMap ( 0xE8,"undef 0xE8" ),
                new vkMap ( 0xE9,"undef 0xE9" ),
                new vkMap ( 0xEA,"undef 0xEA" ),
                new vkMap ( 0xEB,"undef 0xEB" ),
                new vkMap ( 0xEC,"undef 0xEC" ),
                new vkMap ( 0xED,"undef 0xED" ),
                new vkMap ( 0xEE,"undef 0xEE" ),
                new vkMap ( 0xEF,"undef 0xEF" ),
                new vkMap ( 0xF0,"undef 0xF0" ),
                new vkMap ( 0xF1,"undef 0xF1" ),
                new vkMap ( 0xF2,"undef 0xF2" ),
                new vkMap ( 0xF3,"undef 0xF3" ),
                new vkMap ( 0xF4,"undef 0xF4" ),
                new vkMap ( 0xF5,"undef 0xF5" ),
                new vkMap ( 0xF6,"VK_ATTN" ),
                new vkMap ( 0xF7,"VK_CRSEL" ),
                new vkMap ( 0xF8,"VK_EXSEL" ),
                new vkMap ( 0xF9,"VK_EREOF" ),
                new vkMap ( 0xFA,"VK_PLAY" ),
                new vkMap ( 0xFB,"VK_ZOOM" ),
                new vkMap ( 0xFC,"VK_NONAME" ),
                new vkMap ( 0xFD,"VK_PA1" ),
                new vkMap ( 0xFE,"VK_OEM_CLEAR" ),
                new vkMap ( 0xFF,"VK_undef" ),
        };
    }
}
